version: '3.7'
x-common-configs:
  &common
  logging:
    options:
      max-size: '12m'
      max-file: '5'
    driver: json-file
  restart: unless-stopped
  networks:
    - proxy

services:
  ghost:
    <<: *common
    image: ghost:4.11.0-alpine
    container_name: ghost-4.11.0-alpine
    environment:
      - NODE_ENV=production
      - url=https://journal.finndays.com
      - VIRTUAL_HOST=journal.finndays.com
      - LETSENCRYPT_HOST=journal.finndays.com
      - LETSENCRYPT_EMAIL=journal@finndays.com
      - LETSENCRYPT_TEST=true
    expose:
      - 2368
    volumes:
      - /dev/xvdg/ghost/content:/var/lib/ghost/content
      - ./conf/config.production.json:/var/lib/ghost/config.production.json:ro

  nginx-proxy:
    <<: *common
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /dev/xvdg/ssl/certs:/etc/nginx/certs:ro
      - /dev/xvdg/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /dev/xvdg/nginx/conf.d:/etc/nginx/conf.d:rw
      - /dev/xvdg/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro

  letsencrypt:
    <<: *common
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-proxy-le
    volumes:
      - /dev/xvdg/ssl/certs:/etc/nginx/certs:rw
      - /dev/xvdg/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /dev/xvdg/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - nginx-proxy

networks:
  proxy:
    name: nginx-proxy
