version: '3.7'
x-common-configs:
  &common
  logging:
    options:
      max-size: '12m'
      max-file: '5'
    driver: json-file
  restart: unless-stopped
  networks:
    - proxy
    -
services:
  ghost:
    <<: *common
    image: ghost:${GHOST_VERSION}
    container_name: ghost
    env_file:
      - env/ghost.env
    expose:
      - 2368
    volumes:
      - ${MOUNTING_VOLUME}/ghost/content:/var/lib/ghost/content
      - ./conf/ghost.conf.json:/var/lib/ghost/config.production.json:ro

  nginx-proxy:
    <<: *common
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${MOUNTING_VOLUME}/ssl/certs:/etc/nginx/certs:ro
      - ${MOUNTING_VOLUME}/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - ${MOUNTING_VOLUME}/nginx/conf.d:/etc/nginx/conf.d:rw
      - ${MOUNTING_VOLUME}/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro

  letsencrypt:
    <<: *common
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes:
      - ${MOUNTING_VOLUME}/ssl/certs:/etc/nginx/certs:rw
      - ${MOUNTING_VOLUME}/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - ${MOUNTING_VOLUME}/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - nginx-proxy

networks:
  proxy:
    name: nginx-proxy
