version: '3.7'

services:
  ghost:
    image: ghost:3.13.4-alpine
    container_name: ghost-container
    restart: always
    environment:
      - url=http://127.0.0.1:2368
      - NODE_ENV=production
    ports:
      - 2368:2368
    volumes:
      - ./content:/var/lib/ghost/content
      - ./config.base.json:/var/lib/ghost/config.development.json:ro
      - ./config.base.json:/var/lib/ghost/config.production.json:ro
    networks:
      - host

networks:
  host:
