name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: finndays.com
        ssh_private_key: ${{ secrets.FINNDAYS_COM_SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.FINNDAYS_COM_SSH_USER }}
        docker_compose_prefix: finndays_com
        
